//create quit button
var button = ds_map_create()
ds_map_add(button,"color",c_aqua)
ds_map_add(button,"text","Quit Game")
ds_map_add(button,"text_color",c_black)
ds_map_add(button,"pressed",false)
ds_map_add(button,"function","Quit")
ds_map_add(button,"x1",0)
ds_map_add(button,"x2",128)
ds_map_add(button,"y1",0)
ds_map_add(button,"y2",64)
ds_list_add(main_menu,button)
console("Creating Quit Button")
