//create Random Button
var button = ds_map_create()
ds_map_add(button,"color",c_purple)
ds_map_add(button,"text","Pointless Button")
ds_map_add(button,"text_color",c_black)
ds_map_add(button,"pressed",false)
ds_map_add(button,"function","Nothing")
ds_map_add(button,"x1",400)
ds_map_add(button,"x2",550)
ds_map_add(button,"y1",60)
ds_map_add(button,"y2",160)
ds_list_add(main_menu,button)
console("Creating Pointless Button")
