//completely disconnect from a server
network_destroy(client_socket)
ds_stack_pop(menu_stack)
ds_list_clear(playerlist)
ds_list_clear(entity_asteroid_list)
ds_list_clear(entity_ship_list)
ds_list_clear(entity_station_list)
ds_list_clear(entity_vortex_list)
ds_map_destroy(ssn_map)
ssn_map = create_map()
ds_map_destroy(sss_map)
sss_map = create_map()
ds_map_destroy(entity_ship_controllers)
entity_ship_controllers = create_map()
ds_map_destroy(entity_station_controllers)
entity_station_controllers = create_map()
ds_list_destroy(sketch_list)
