//Packet Names
enum packet
    {
    null,
    chat_send,
    chat_broadcast,
    
    entity_create_projectile,
    entity_create_object,
    entity_create_asteroid,
    entity_create_ship,
    entity_create_station,
    entity_create_star,
    entity_create_vortex,
    
    entity_destroy_projectile,
    entity_destroy_object,
    entity_destroy_asteroid,
    entity_destroy_ship,
    entity_destroy_station,
    entity_destroy_star,
    entity_destroy_vortex,
    
    entity_load_projectile,
    entity_load_object,
    entity_load_asteroid,
    entity_load_ship,
    entity_load_station,
    entity_load_star,
    entity_load_vortex,
    
    entity_update_projectile,
    entity_update_object,
    entity_update_asteroid,
    entity_update_ship,
    entity_update_station,
    entity_update_star,
    entity_update_vortex,
    
    entity_ship_action,
    entity_ship_set_control,
    kick,
    player_request_entity_control,
    sss_add,
    sss_assign,
    sss_load,
    sss_remove,
    ping_request,
    ping_tell,
    }
