function_list = ds_list_create()
ds_list_add(function_list,"Back")
ds_list_add(function_list,"Quit")
ds_list_add(function_list,"Restart")
ds_list_add(function_list,"Host")
ds_list_add(function_list,"Client")
ds_list_add(function_list,"Delete_Config")
ds_list_add(function_list,"edit_button_color")
ds_list_add(function_list,"edit_button_text")
ds_list_add(function_list,"edit_text_color")
ds_list_add(function_list,"edit_button_function")
ds_list_add(function_list,"firework")
ds_list_add(function_list,"edit_pause_text")
